name: Push trigger for swift-library

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - hotfix/**
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - develop
      - feature/**
      - hotfix/**

jobs:
  build-swift:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: list available schemes
        run: xcodebuild -list -json

      - name: Build project
        run: xcodebuild -scheme VCIClient -destination 'generic/platform=iOS' build

      - name: Run tests
        run: xcodebuild test -scheme VCIClientTests -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
        if: "${{ github.event_name != 'pull_request' && failure() }}"
